// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package account

import (
	"goframe/internal/infra/data/ent"
)

// Injectors from wire.go:

func InitAccount(db *ent.Client) *controller {
	accountDao := ProviderDao(db)
	accountLogic := ProviderService(accountDao)
	accountController := ProviderHandler(accountLogic)
	return accountController
}
